### ISSUE TITLE
Security: NULL Pointer Dereference in the function aes256_encrypt()

### ISSUE THREAD

**Issue by UVScan** [Samsung/mTower#75]
# Affected components

affected source code file: tools/ecdsa_keygen.c

# Attack vector(s)

Lacking a check for the return value of EVP_CIPHER_CTX_new. 
EVP_CIPHER_CTX_new() returns a pointer to a newly created EVP_CIPHER_CTX for success and NULL for failure.

# Suggested description of the vulnerability for use in the CVE

Null pointer dereference vulnerability in aes256_encrypt() function in Samsung Electronics mTower v0.3.0 (and earlier) due to a missing check on the return value of EVP_CIPHER_CTX_new. 

# Discoverer(s)/Credits

UVScan

# Reference(s)
https://www.openssl.org/docs/manmaster/man3/EVP_CIPHER_CTX_new.html

https://github.com/Samsung/mTower/blob/18f4b592a8a973ce5972f4e2658ea0f6e3686284/tools/ecdsa_keygen.c#L135

**Comment by tdrozdovsky** [comment]
The issue will be reviewed and fixed as soon as possible.
