### ISSUE TITLE
External structure modification within printf system call in mTower v0.3.0

### ISSUE THREAD

**Issue by SyzTrust** [Samsung/mTower#94]
Hi there,
We are currently testing mTower v0.3.0 on GitHub and have encountered a perplexing bug. During our testing, we discovered that an external structure can be modified within the printf system call.

Before debugging this issue, we added a `printf` function to the `tee/lib/libutils/isoc/include/sys/queue.h` file. The added code is as follows:

```c
#define TAILQ_REMOVE(head, elm, field) do {             \
    QUEUEDEBUG_TAILQ_PREREMOVE((head), (elm), field)        \
    printf("elm->field is at %p and is %p\n",&elm->field,elm->field); \
    QUEUEDEBUG_TAILQ_OP((elm), field)               \
    if (((elm)->field.tqe_next) != NULL)                \
        (elm)->field.tqe_next->field.tqe_prev =         \
            (elm)->field.tqe_prev;              \
    else                                \
        (head)->tqh_last = (elm)->field.tqe_prev;       \
    *(elm)->field.tqe_prev = (elm)->field.tqe_next;         \
    QUEUEDEBUG_TAILQ_POSTREMOVE((elm), field);          \
} while (/* CONSTCOND */0)
```

**We have documented our debugging process in detail** in this [Google Doc](https://docs.google.com/document/d/1UHZdVy0KRAU0e8RdLpzp96uPygfeRSvmgXXTqvZpZpA/edit?usp=sharing).

We are unsure if this issue is caused by the code provided by the project or by a base library. Therefore, we would appreciate your insights into the issue. If there are any details we have overlooked or missed, please let us know. We would be grateful for any guidance you can offer.

Best regards, 
SyzTrust

**Comment by tdrozdovsky** [comment]
Will be reviewed soon

**Comment by tdrozdovsky** [comment]
Replaced the standard printf function with a static printf implementation without using system call. This also reduced the size of binary files
